title: "lichodev's vault"
email: marchionni.lisandro@gmail.com
timezone: UTC-3
baseurl: "/wiki"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: lichodev
paginate: 30
locale: es_us
lang: es_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: lichodev
    display_name: Lisandro Marchionni
    avatar: "assets/images/sal.png"
    email: marchionni.lisandro@gmail.com
    web: marchionni.ml
    # twitter: https://twitter.com/wowthemesnet
    # description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

# Social
social:
  instagram: https://www.instagram.com/licha.marcho/
  #facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  #twitter: https://twitter.com/bstartercom

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
